export enum ActionType {
  APPROVE_NFT = "APPROVE_NFT",
  APPROVE_TOKEN = "APPROVE_TOKEN",
  FETCH_LISTED_NFTS = "FETCH_LISTED_NFTS",
  FETCH_USERS_NFTS = "FETCH_USERS_NFTS",
  SET_BIRD_SKIN = "SET_BIRD_SKIN",
}
